// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package loadstress_messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The type of payload that should be returned.
type PayloadType int32

const (
	// Compressable text format.
	PayloadType_COMPRESSABLE PayloadType = 0
	// Uncompressable binary format.
	PayloadType_UNCOMPRESSABLE PayloadType = 1
	// Randomly chosen from all other formats defined in this enum.
	PayloadType_RANDOM PayloadType = 2
)

var PayloadType_name = map[int32]string{
	0: "COMPRESSABLE",
	1: "UNCOMPRESSABLE",
	2: "RANDOM",
}

var PayloadType_value = map[string]int32{
	"COMPRESSABLE":   0,
	"UNCOMPRESSABLE": 1,
	"RANDOM":         2,
}

func (x PayloadType) String() string {
	return proto.EnumName(PayloadType_name, int32(x))
}

func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type RetStatus int32

const (
	RetStatus_SUCCESS        RetStatus = 0
	RetStatus_CALL_FAILED    RetStatus = 1
	RetStatus_CALL_TIMEOUT   RetStatus = 2
	RetStatus_CALL_RET_ERROR RetStatus = 3
)

var RetStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "CALL_FAILED",
	2: "CALL_TIMEOUT",
	3: "CALL_RET_ERROR",
}

var RetStatus_value = map[string]int32{
	"SUCCESS":        0,
	"CALL_FAILED":    1,
	"CALL_TIMEOUT":   2,
	"CALL_RET_ERROR": 3,
}

func (x RetStatus) String() string {
	return proto.EnumName(RetStatus_name, int32(x))
}

func (RetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

type Payload struct {
	// The type of data in body.
	Type PayloadType `protobuf:"varint,1,opt,name=type,proto3,enum=loadstress.messages.PayloadType" json:"type,omitempty"`
	// Primary contents of payload.
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetType() PayloadType {
	if m != nil {
		return m.Type
	}
	return PayloadType_COMPRESSABLE
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SimpleRequest struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	ReqSize              int64    `protobuf:"varint,2,opt,name=req_size,json=reqSize,proto3" json:"req_size,omitempty"`
	Payload              *Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (m *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(m, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *SimpleRequest) GetReqSize() int64 {
	if m != nil {
		return m.ReqSize
	}
	return 0
}

func (m *SimpleRequest) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SimpleResponse struct {
	RespId               int64    `protobuf:"varint,1,opt,name=resp_id,json=respId,proto3" json:"resp_id,omitempty"`
	ReqSize              int64    `protobuf:"varint,2,opt,name=req_size,json=reqSize,proto3" json:"req_size,omitempty"`
	Elapse               int64    `protobuf:"varint,3,opt,name=elapse,proto3" json:"elapse,omitempty"`
	Payload              *Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetRespId() int64 {
	if m != nil {
		return m.RespId
	}
	return 0
}

func (m *SimpleResponse) GetReqSize() int64 {
	if m != nil {
		return m.ReqSize
	}
	return 0
}

func (m *SimpleResponse) GetElapse() int64 {
	if m != nil {
		return m.Elapse
	}
	return 0
}

func (m *SimpleResponse) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CallResult struct {
	Resp                 *SimpleResponse `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Status               RetStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=loadstress.messages.RetStatus" json:"status,omitempty"`
	Errmsg               string          `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Elapsed              uint64          `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CallResult) Reset()         { *m = CallResult{} }
func (m *CallResult) String() string { return proto.CompactTextString(m) }
func (*CallResult) ProtoMessage()    {}
func (*CallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *CallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResult.Unmarshal(m, b)
}
func (m *CallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResult.Marshal(b, m, deterministic)
}
func (m *CallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResult.Merge(m, src)
}
func (m *CallResult) XXX_Size() int {
	return xxx_messageInfo_CallResult.Size(m)
}
func (m *CallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResult.DiscardUnknown(m)
}

var xxx_messageInfo_CallResult proto.InternalMessageInfo

func (m *CallResult) GetResp() *SimpleResponse {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *CallResult) GetStatus() RetStatus {
	if m != nil {
		return m.Status
	}
	return RetStatus_SUCCESS
}

func (m *CallResult) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *CallResult) GetElapsed() uint64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func init() {
	proto.RegisterEnum("loadstress.messages.PayloadType", PayloadType_name, PayloadType_value)
	proto.RegisterEnum("loadstress.messages.RetStatus", RetStatus_name, RetStatus_value)
	proto.RegisterType((*Payload)(nil), "loadstress.messages.Payload")
	proto.RegisterType((*SimpleRequest)(nil), "loadstress.messages.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "loadstress.messages.SimpleResponse")
	proto.RegisterType((*CallResult)(nil), "loadstress.messages.CallResult")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0x8e, 0x2c, 0x55, 0x6a, 0x46, 0xa9, 0x2a, 0xa6, 0xb4, 0x75, 0xa1, 0x14, 0xe3, 0x5e, 0x4c,
	0x0e, 0x3e, 0xb8, 0x25, 0x3d, 0x16, 0x57, 0x51, 0xc1, 0x60, 0x47, 0x61, 0xd6, 0x3e, 0x1b, 0x05,
	0x0f, 0xc1, 0x20, 0x57, 0xf2, 0xce, 0xfa, 0xa0, 0x3c, 0x47, 0xdf, 0xa3, 0xaf, 0x58, 0xb4, 0xb6,
	0xda, 0x04, 0x8c, 0x21, 0x37, 0xcd, 0x37, 0xdf, 0x7c, 0x3f, 0x68, 0x21, 0xda, 0xb0, 0x48, 0x7e,
	0xcf, 0x32, 0xac, 0x74, 0x69, 0x4a, 0x7c, 0x53, 0x94, 0xf9, 0x4a, 0x8c, 0x66, 0x91, 0x61, 0xbb,
	0xea, 0x2b, 0x08, 0x6e, 0xf3, 0xba, 0xd9, 0xe0, 0x57, 0xf0, 0x4c, 0x5d, 0x71, 0xd7, 0xe9, 0x39,
	0x83, 0x68, 0xd4, 0x1b, 0x1e, 0xa1, 0x0f, 0x0f, 0xdc, 0x79, 0x5d, 0x31, 0x59, 0x36, 0x22, 0x78,
	0x77, 0xe5, 0xaa, 0xee, 0x76, 0x7a, 0xce, 0xe0, 0x82, 0xec, 0x77, 0xbf, 0x86, 0x57, 0x6a, 0xbd,
	0xa9, 0x0a, 0x26, 0xde, 0xee, 0x58, 0x0c, 0xbe, 0x05, 0x5f, 0xf3, 0x76, 0xb9, 0x5e, 0x59, 0x71,
	0x97, 0x5e, 0x68, 0xde, 0x4e, 0x56, 0xf8, 0x01, 0x5e, 0x36, 0xb0, 0xac, 0x1f, 0xd8, 0xde, 0xbb,
	0x14, 0x68, 0xde, 0xaa, 0xf5, 0x03, 0xe3, 0x15, 0x04, 0xd5, 0xde, 0xab, 0xeb, 0xf6, 0x9c, 0x41,
	0x38, 0xfa, 0x78, 0x2a, 0x0f, 0xb5, 0xe4, 0xfe, 0x6f, 0x07, 0xa2, 0xd6, 0x5b, 0xaa, 0xf2, 0x97,
	0x30, 0xbe, 0x87, 0x40, 0xb3, 0x54, 0xff, 0xdd, 0xfd, 0x66, 0x3c, 0x6d, 0xff, 0x0e, 0x7c, 0x2e,
	0xf2, 0x4a, 0xd8, 0xba, 0xbb, 0x74, 0x98, 0x1e, 0xc7, 0xf2, 0x9e, 0x13, 0xeb, 0x8f, 0x03, 0x90,
	0xe4, 0x45, 0x41, 0x2c, 0xbb, 0xc2, 0xe0, 0x37, 0xf0, 0x9a, 0x0c, 0x36, 0x4f, 0x38, 0xfa, 0x7c,
	0x54, 0xe3, 0x69, 0x0b, 0xb2, 0x07, 0x78, 0x05, 0xbe, 0x98, 0xdc, 0xec, 0xc4, 0x06, 0x8e, 0x46,
	0x9f, 0x8e, 0x9e, 0x12, 0x1b, 0x65, 0x59, 0x74, 0x60, 0xdb, 0x3e, 0x5a, 0x6f, 0xe4, 0xde, 0xf6,
	0x39, 0xa7, 0xc3, 0x84, 0x5d, 0x08, 0xf6, 0xcd, 0xf6, 0x7d, 0x3c, 0x6a, 0xc7, 0xcb, 0xef, 0x10,
	0x3e, 0xfa, 0xd9, 0x18, 0xc3, 0x45, 0x92, 0xcd, 0x6e, 0x29, 0x55, 0x6a, 0xfc, 0x63, 0x9a, 0xc6,
	0x67, 0x88, 0x10, 0x2d, 0x6e, 0x9e, 0x60, 0x0e, 0x02, 0xf8, 0x34, 0xbe, 0xb9, 0xce, 0x66, 0x71,
	0xe7, 0x32, 0x83, 0xf3, 0x7f, 0x39, 0x30, 0x84, 0x40, 0x2d, 0x92, 0x24, 0x55, 0x2a, 0x3e, 0xc3,
	0xd7, 0x10, 0x26, 0xe3, 0xe9, 0x74, 0xf9, 0x73, 0x3c, 0x99, 0xa6, 0xd7, 0xb1, 0x63, 0xc5, 0x1b,
	0x60, 0x3e, 0x99, 0xa5, 0xd9, 0x62, 0x1e, 0x77, 0x1a, 0x71, 0x8b, 0x50, 0x3a, 0x5f, 0xa6, 0x44,
	0x19, 0xc5, 0xee, 0x9d, 0x6f, 0x9f, 0xf1, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xfe,
	0xcb, 0x7a, 0xd8, 0x02, 0x00, 0x00,
}
